// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProyectoTI_PRR_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoTI_PRR_Backend.Models.Cliente", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cedula");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProyectoTI_PRR_Backend.Models.Cotizacion", b =>
                {
                    b.Property<string>("NumeroCot")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClienteCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("NumeroCot");

                    b.HasIndex("ClienteCedula");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("ProyectoTI_PRR_Backend.Models.CotizacionMaterial", b =>
                {
                    b.Property<string>("CotizacionNumero")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialCodigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.HasKey("CotizacionNumero", "MaterialCodigo");

                    b.HasIndex("MaterialCodigo");

                    b.ToTable("CotizacionMateriales");
                });

            modelBuilder.Entity("ProyectoTI_PRR_Backend.Models.Material", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CostoSinIva")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("ProyectoTI_PRR_Backend.Models.Cotizacion", b =>
                {
                    b.HasOne("ProyectoTI_PRR_Backend.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoTI_PRR_Backend.Models.CotizacionMaterial", b =>
                {
                    b.HasOne("ProyectoTI_PRR_Backend.Models.Cotizacion", "Cotizacion")
                        .WithMany()
                        .HasForeignKey("CotizacionNumero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoTI_PRR_Backend.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cotizacion");

                    b.Navigation("Material");
                });
#pragma warning restore 612, 618
        }
    }
}
